name: GitHub Actions Demo

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 20
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          node-version: 20

      - name: Build
        run: dotnet build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 20

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          node-version: 20

      - name: Build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o ${{ github.workspace }}/publish
          
      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v2
        with:
          app-name: 'APIResorty'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2030ec6c7f684188ab8af2321dd8d53b }}  # profil publikacji aplikacji Azure, przechowywany jako sekret w ustawieniach repozytorium
          package: ./publish
          
